/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "ROBOTWEALTH_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "fetchRW": {
      "name": string
      "type": "sst.aws.Function"
    }
  }
}

import "sst"
export {}