/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "EXTENDED_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "EXTENDED_LAMBDA_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "EXTENDED_STARKEX_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FailureTopic": {
      "arn": string
      "type": "sst.aws.SnsTopic"
    }
    "HYPERLIQUID_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "HYPERLIQUID_WALLET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ROBOTWEALTH_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SUPABASE_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TELEGRAM_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TELEGRAM_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TimestampChecker": {
      "name": string
      "type": "sst.aws.Function"
    }
    "notifier": {
      "name": string
      "type": "sst.aws.Function"
    }
    "tradeExtended": {
      "name": string
      "type": "sst.aws.Function"
    }
    "tradeHyperliquid": {
      "name": string
      "type": "sst.aws.Function"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}